/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odev2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author melikekecelioglu
 */
public class Q2 extends javax.swing.JFrame {

    /**
     * Creates new form QuestionB
     */
    ArrayList<Person> appliers;

    public Q2() {
        initComponents();
        appliers = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtp_password = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtf_phone = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        rbtn_genderMale = new javax.swing.JRadioButton();
        rbtn_genderFemale = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        chbx_isSmoker = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(204, 0, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 153, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel1.setText("Mail");
        jPanel4.add(jLabel1);

        txt_mail.setColumns(10);
        txt_mail.setText("jTextField1");
        jPanel4.add(txt_mail);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 51, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel2.setText("Name Surname");
        jPanel5.add(jLabel2);

        txt_nameSurname.setColumns(10);
        txt_nameSurname.setText("jTextField2");
        jPanel5.add(txt_nameSurname);

        jPanel2.add(jPanel5);

        jPanel10.setBackground(new java.awt.Color(255, 0, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel3.setText("Password");
        jPanel10.add(jLabel3);

        txtp_password.setColumns(10);
        txtp_password.setText("jPasswordField1");
        jPanel10.add(txtp_password);

        jPanel2.add(jPanel10);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel4.setText("Phone");
        jPanel6.add(jLabel4);

        try {
            txtf_phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txtf_phone);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 60));

        buttonGroup1.add(rbtn_genderMale);
        rbtn_genderMale.setText("Male");
        jPanel7.add(rbtn_genderMale);

        buttonGroup1.add(rbtn_genderFemale);
        rbtn_genderFemale.setText("Female");
        jPanel7.add(rbtn_genderFemale);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 60));

        chbx_isSmoker.setText("Is Smoker");
        jPanel8.add(chbx_isSmoker);

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 255, 153));
        jPanel3.setMinimumSize(new java.awt.Dimension(120, 420));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 420));
        jPanel3.setSize(new java.awt.Dimension(120, 420));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean Register() {
        String mail;
        String nameSurname;
        String password;
        String phone;
        char gender;
        boolean isSmoker;
        boolean rvalue = false;

        if (txt_mail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill mail area! ");
            return rvalue;
        }
        if (txt_nameSurname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill name surname area! ");
            return rvalue;
        }
        if (txtp_password.getText().isEmpty() || txtf_phone.getText().isEmpty() || !(rbtn_genderFemale.isSelected() || rbtn_genderMale.isSelected())) {
            JOptionPane.showMessageDialog(rootPane, "Please fill other area! ");
            return rvalue;
        }
        if (!txtf_phone.isEditValid()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter correct number! ");
            return rvalue;
        }
        String rpassword = JOptionPane.showInputDialog(rootPane, "Please enter password again", "Please retype", JOptionPane.INFORMATION_MESSAGE);
        mail = txt_mail.getText();
        nameSurname = txt_nameSurname.getText();
        password = txtp_password.getPassword().toString();
        String spassword = txtf_phone.getText();
        phone = txtf_phone.getText();
        if (rbtn_genderMale.isSelected()) {
            gender = 'M';
        } else {
            gender = 'F';
        }
        isSmoker = chbx_isSmoker.isSelected();

        if (rpassword.compareTo(spassword) != 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter correct numbers ", "Password", JOptionPane.ERROR_MESSAGE);
            return rvalue;
        }

        int value = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to apply?", "Apply", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (value == JOptionPane.NO_OPTION) {
            return rvalue;
        }

        Person nPerson = new Person();
        nPerson.mail = mail;
        nPerson.nameSurname = nameSurname;
        nPerson.password = password;
        nPerson.phone = phone;
        nPerson.gender = gender;
        nPerson.isSmoker = isSmoker;

        this.appliers.add(nPerson);
        rvalue = true;
        return rvalue;

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Register();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        int value = JOptionPane.showConfirmDialog(rootPane, "Do you want to save your application before closing?", "Warning!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (value == JOptionPane.YES_OPTION) {
            if (Register()) {
                this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            } else {
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else if (value == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }


    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Q2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbx_isSmoker;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton rbtn_genderFemale;
    private javax.swing.JRadioButton rbtn_genderMale;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nameSurname;
    private javax.swing.JFormattedTextField txtf_phone;
    private javax.swing.JPasswordField txtp_password;
    // End of variables declaration//GEN-END:variables
}
