/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odev2;

import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author melikekecelioglu
 */
public class Q4 extends javax.swing.JFrame {
    String text;
    /**
     * Creates new form Q4
     */
    public Q4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_menu = new javax.swing.JPopupMenu();
        mitem_popupMenuCut = new javax.swing.JMenuItem();
        mitem_popupMenuCopy = new javax.swing.JMenuItem();
        mitem_popupMenuPaste = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_text = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitem_fileSave = new javax.swing.JMenuItem();
        mitem_fileClose = new javax.swing.JMenuItem();
        mitem_editPaste = new javax.swing.JMenu();
        mitem_editCut = new javax.swing.JMenuItem();
        mitem_editCopy = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        mitem_popupMenuCut.setText("cut");
        mitem_popupMenuCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuCutActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupMenuCut);

        mitem_popupMenuCopy.setText("copy");
        mitem_popupMenuCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuCopyActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupMenuCopy);

        mitem_popupMenuPaste.setText("paste");
        mitem_popupMenuPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuPasteActionPerformed(evt);
            }
        });
        popup_menu.add(mitem_popupMenuPaste);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta_text.setColumns(20);
        txta_text.setLineWrap(true);
        txta_text.setRows(5);
        txta_text.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        txta_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txta_textMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txta_textMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txta_text);

        jMenu1.setText("File");

        mitem_fileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mitem_fileSave.setText("Save");
        mitem_fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_fileSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mitem_fileSave);

        mitem_fileClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mitem_fileClose.setText("Close");
        mitem_fileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_fileCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mitem_fileClose);

        jMenuBar1.add(jMenu1);

        mitem_editPaste.setText("Edit");

        mitem_editCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mitem_editCut.setText("Cut");
        mitem_editCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuCutActionPerformed(evt);
            }
        });
        mitem_editPaste.add(mitem_editCut);

        mitem_editCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mitem_editCopy.setText("Copy");
        mitem_editCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuCopyActionPerformed(evt);
            }
        });
        mitem_editPaste.add(mitem_editCopy);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Paste");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_popupMenuPasteActionPerformed(evt);
            }
        });
        mitem_editPaste.add(jMenuItem3);

        jMenuBar1.add(mitem_editPaste);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitem_fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_fileSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mitem_fileSaveActionPerformed

    private void mitem_fileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_fileCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mitem_fileCloseActionPerformed

    private void txta_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txta_textMousePressed
        // TODO add your handling code here:
        if(SwingUtilities.isRightMouseButton(evt)){
            showPopUp(evt);
        }
    }//GEN-LAST:event_txta_textMousePressed

    private void txta_textMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txta_textMouseReleased
        // TODO add your handling code here:
         if(SwingUtilities.isRightMouseButton(evt)){
            showPopUp(evt);
        }
    }//GEN-LAST:event_txta_textMouseReleased

    private void mitem_popupMenuCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupMenuCutActionPerformed
        // TODO add your handling code here:
        this.text=txta_text.getSelectedText();
        txta_text.replaceSelection("");
    }//GEN-LAST:event_mitem_popupMenuCutActionPerformed

    private void mitem_popupMenuCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupMenuCopyActionPerformed
        // TODO add your handling code here:
         this.text=txta_text.getSelectedText();
    }//GEN-LAST:event_mitem_popupMenuCopyActionPerformed

    private void mitem_popupMenuPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_popupMenuPasteActionPerformed
        // TODO add your handling code here:
        txta_text.insert(text, txta_text.getSelectionStart());
    }//GEN-LAST:event_mitem_popupMenuPasteActionPerformed
    private void showPopUp(MouseEvent evt){
        if(evt.isPopupTrigger()){
           popup_menu.show(evt.getComponent(),evt.getX(),evt.getY()); 
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Q4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mitem_editCopy;
    private javax.swing.JMenuItem mitem_editCut;
    private javax.swing.JMenu mitem_editPaste;
    private javax.swing.JMenuItem mitem_fileClose;
    private javax.swing.JMenuItem mitem_fileSave;
    private javax.swing.JMenuItem mitem_popupMenuCopy;
    private javax.swing.JMenuItem mitem_popupMenuCut;
    private javax.swing.JMenuItem mitem_popupMenuPaste;
    private javax.swing.JPopupMenu popup_menu;
    private javax.swing.JTextArea txta_text;
    // End of variables declaration//GEN-END:variables
}
